apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
- name: kallepan/oe-frontend
  newName: kallepan/oe-frontend
  newTag: IMAGE_TAG