apiVersion: v1
kind: Service
metadata:
  labels:
    app: vargen-angular
    tier: frontend
  name: vargen-frontend
  namespace: genetics
spec:
  ports:
  - name: web
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vargen-angular
    tier: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vargen-angular
    tier: frontend
  name: vargen-frontend
  namespace: genetics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vargen-angular
  template:
    metadata:
      labels:
        app: vargen-angular
        tier: frontend
    spec:
      containers:
      - image: kallepan/vargen-frontend:dev
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /usr/bin/nginx
              - -s
              - quit
        livenessProbe:
          httpGet:
            path: /
            port: 80
        name: vargen-angular
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          timeoutSeconds: 5
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 512Mi
        securityContext:
          allowPrivilegeEscalation: false
      imagePullSecrets:
      - name: regcred
